### ISSUE TITLE
Docker DEV issues: Audit/Replic, Minio Container

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1010]
Terry and Ashley were attempting to test some Audit/Replic behaviors in the docker stack and encountered some issues
- [x] Minio container is redirecting to a dynamic port rather than allowing login
  - https://github.com/CDLUC3/merritt-docker/commit/bffc9e26f0645c189eaaa6bedd224a434b8c289b 
- [x] Audit state command AND unpause command have errors (rebuild likely needed)
  - https://github.com/CDLUC3/mrt-audit/pull/11
- [x] Replic state command AND unpause command have errors (rebuild likely needed)
  - https://github.com/CDLUC3/mrt-replic/pull/9

**Comment by terrywbrady** [comment]
Will need help from @dloy  on this.  The container cannot connect to the database.

```
ERROR [http-nio-8080-exec-1] (HikariPool.java:594) - HikariPool-1 - Exception during pool initialization.
MrtConnectionPool Exception:org.cdlib.mrt.audit.db.FixityConnectionPool-<init>:123 GENERAL_EXCEPTION[Unexpected Programmic exception] com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
org.cdlib.mrt.audit.db.FixityConnectionPool-<init>:123 GENERAL_EXCEPTION[Unexpected Programmic exception] com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: null
        at org.cdlib.mrt.audit.db.FixityConnectionPool.getFixityConnectionPool(FixityConnectionPool.java:69)
        at org.cdlib.mrt.audit.db.FixityItemDB.setPool(FixityItemDB.java:152)
        at org.cdlib.mrt.audit.db.FixityItemDB.<init>(FixityItemDB.java:79)
        at org.cdlib.mrt.audit.service.FixityServiceConfig.setFixityItemDB(FixityServiceConfig.java:258)
        at org.cdlib.mrt.audit.service.FixityServiceConfig.<init>(FixityServiceConfig.java:137)
        at org.cdlib.mrt.audit.service.FixityServiceConfig.useYaml(FixityServiceConfig.java:106)
        at org.cdlib.mrt.audit.app.FixityServiceInit.<init>(FixityServiceInit.java:116)
        at org.cdlib.mrt.audit.app.FixityServiceInit.getFixityServiceInit(FixityServiceInit.java:78)
        at org.cdlib.mrt.audit.app.jersey.fixity.JerseyFixity.getServiceStatus(JerseyFixity.java:272)
```

**Comment by terrywbrady** [comment]
## Differences between INV and Audit connector
- https://github.com/CDLUC3/mrt-inventory/blob/8f62d21941dbec7da895b3afe9370167a17ea17b/inv-src/src/main/java/org/cdlib/mrt/inv/utility/HikariConnectionPool.java#L85
- https://github.com/CDLUC3/mrt-audit/blob/132353dfd4a4c80971269b5dc84acf496896530a/audit-src/src/main/java/org/cdlib/mrt/audit/db/FixityConnectionPool.java#L100

## Differences between INV and Audit pom
- https://github.com/CDLUC3/mrt-inventory/blob/6aed400e4d44275614b3b971473fc8e83d2fcfb5/inv-src/pom.xml#L141-L145
- https://github.com/CDLUC3/mrt-audit/blob/1773a18c29707088b45a36c49f67c4fde702b0ba/audit-src/pom.xml#L90-L95

I am not sure we should be running `mysql-connector-java:8.0.18` with mysql 5.

**Comment by terrywbrady** [comment]
To resolve the audit state issue

```
  db:
    adapter: mysql2
    host: db-container
    name: db-name
    user: ***
    password: ***
    #encoding: "characterEncoding=UTF-8&characterSetResults=UTF-8&enabledTLSProtocols=TLSv1.2"   # schema won't load if it's utf8mb4
    encoding: "characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false"   # schema won't load if it's utf8mb4
```
Solution discovered from the following comment.

- https://stackoverflow.com/a/67438592/3846548
