### ISSUE TITLE
Correct UCB createmarc Key error

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1099]
Key error occurs when createmarc.py runs. Note that the MARC record is generated successfully. However the key error prevents createmarc.py from removing ETD zips during its cleanup process.
```
Starting createmarc at Tue Jun 14 13:30:01 PDT 2022
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 980, in <module>
    main()
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 975, in main
    delete_working_files(hostenv)
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 407, in delete_working_files
    ok_to_delete = check_if_ok_to_delete(zipfilename, hostenv)
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 367, in check_if_ok_to_delete
    if campus_configs[campusabbr]['create_marc']:
KeyError: 'berkeley'
Finished createmarc at Tue Jun 14 13:40:06 PDT 2022
```
Terry and I are going to meet on Monday 6/27 to address this. In the meantime he will manually back up and delete zips anytime a new UCB ETD is ingested and published.

**Comment by elopatin-uc3** [comment]
Fix deployed for above KeyError:
https://github.com/CDLUC3/uc3-etds/pull/19

The createmarc script ran successfully. Today's production run included one UCB ETD record, 171 records for UCSD and 36 records for UC Merced.
