### ISSUE TITLE
ETDs ingest process has been failing since Sat. 7/23

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1181]
Discovered on 7/31: ETDs ingest process (getetds.py) has stalled on an XML parsing issue as of 7/23.

```
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 334, in <module>
    main()
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 322, in main
    (merritt_pm_list, pq_md_list) = extract_metadata(hostenv)
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 191, in extract_metadata
    dom = ET.fromstring(pqstring)
  File "src/lxml/etree.pyx", line 3222, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 74
lxml.etree.XMLSyntaxError: xmlParseCharRef: invalid xmlChar value 65534, line 74, column 110
```

**Comment by elopatin-uc3** [comment]
Added print statement to obtain names of PQ XML files being parsed as script iterates through all available ETD zips in the zipfiles directory.

Parsing halts at admin upload ..._885390.zip

**Comment by elopatin-uc3** [comment]
What appeared to be three examples of problematic character encoding occurred in the abstract section for the above ETD's XML file. I backed up the zip in the failures directory, removed these character sequences from the XML and then re-ran the getetds.py script. It completed parsing the XML files in all ETD zips in the zipfiles directory. 

Monitoring ingests now.

**Comment by elopatin-uc3** [comment]
Ingests completed
