### ISSUE TITLE
Lock wait failures on prod inventory

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1196]
Scott identified a number of reported inventory failures from Dryad customers:
~~~
[sfisher](https://app.slack.com/team/U02UBR3EL)
  [1:27 PM](https://cdlib.slack.com/archives/C86U0VBLH/p1660854436062519)
Hi Merritt, folks.  I'm just checking in that the processing machinery is working correctly the last couple days (I think a few this morning and one from yesterday).  We had a few reports from curators that some things that were submitted through SWORD still haven't become available.  I checked on our side and we got success responses from SWORD but they do not show up in the Merritt UI and probably never made it into the OAI PMH feed. (edited) 
[1:29](https://cdlib.slack.com/archives/C86U0VBLH/p1660854562069329)
This is the information on the three curators mentioned.
ark:/13030/m593822z -- version 2 never processed
ark:/13030/m5jm9jgv -- version 2 never processed
http://merritt.cdlib.org/d/ark%3A%2F13030%2Fm5z96m8g -- this is version 1 and never processed
~~~

A review of the inv logs from yesterday indicated a number of "Lock wait timeout exceed" exceptions: 
705 inv01, 790 inv02. Note these counts may include duplicates and do NOT necessarily represent objects that failed.  Later resubmissions may have corrected some of these problems.

Example:
~~~
Wed Aug 17 05:58:52 PDT 2022 ** (05) [yyMMdd] org.cdlib.mrt.db.DBUtil-exec:133 SQL_EXCEPTION[SQL exception] Exception - sql=update inv_nodes_inv_objects set version_number='60',replicated=null,inv_node_id='12',replic_start='2022-08-10 21:03:49',created='2016-11-05 00:00:28',role='primary',completion_status='ok',replic_size='65598',inv_object_id='1741078' where id=6677856 - exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction - Exception:com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
        at org.cdlib.mrt.db.DBUtil.exec(DBUtil.java:133)
        at org.cdlib.mrt.inv.utility.DBAdd.update(DBAdd.java:224)
        at org.cdlib.mrt.inv.action.SaveObject.setNode(SaveObject.java:733)
        at org.cdlib.mrt.inv.action.SaveObject.setObject(SaveObject.java:537)
        at org.cdlib.mrt.inv.action.SaveObject.process(SaveObject.java:400)
        at org.cdlib.mrt.inv.action.SaveObject.process(SaveObject.java:381)
        at org.cdlib.mrt.inv.action.ProcessItem.saveObjectRetry404(ProcessItem.java:188)
        at org.cdlib.mrt.inv.action.ProcessItem.process(ProcessItem.java:165)
        at org.cdlib.mrt.inv.action.ProcessItem.run(ProcessItem.java:142)
        at java.lang.Thread.run(Thread.java:750)
~~~

**Comment by dloy** [comment]
From: https://severalnines.com/blog/how-fix-lock-wait-timeout-exceeded-error-mysql/
 The above simply means the transaction has reached the innodb_lock_wait_timeout while waiting to obtain an exclusive lock which defaults to 50 seconds. The common causes are:

- The offensive transaction is not fast enough to commit or rollback the transaction within innodb_lock_wait_timeout duration.
- The offensive transaction is waiting for row lock to be released by another transaction.

**Comment by dloy** [comment]
I am fairly certain the number of lock timeouts we saw on 8/17 are load related. One reason for the timeout occurs  when the "transaction is not fast enough to commit'. The current  timeout is set for 50 secs.  Our current objects may have hundreds of files. Each file corresponds to a an audit row. Additional time is used in the construction of row elements that are built by reading system/mrt-* files. With retries caused by caching problems with Minio could impact this amount Suggest:
~~~
innodb_lock_wait_timeout=100
~~~
 from the current 50
This change should be set globally because of the SYSTEM_VARIABLES_ADMIN permission needed to set temporarily for a specific jobs.

**Comment by terrywbrady** [comment]
Inv01
```
grep -c "Lock wait timeout exceeded" inv*|grep -v ":0$"
inv220526.log:10
inv220712.log:10
inv220725.log:20
inv220729.log:30
inv220802.log:10
inv220808.log:5
inv220812.log:10
inv220813.log:5
inv220815.log:30
inv220816.log:10
inv220817.log:705
inv220818.log:1385
inv220819.log:1270
inv220826.log:5
```

Inv02
```
grep -c "Lock wait timeout exceeded" inv*|grep -v ":0$"
inv220526.log:5
inv220721.log:5
inv220725.log:10
inv220726.log:5
inv220731.log:5
inv220802.log:5
inv220808.log:25
inv220811.log:5
inv220812.log:5
inv220813.log:5
inv220814.log:5
inv220815.log:50
inv220816.log:5
inv220817.log:790
inv220818.log:2210
inv220819.log:1435
```
