### ISSUE TITLE
ETD harvest: Intermittent 'Connection reset by peer' error

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1220]
As of the week of 8/29, the PAD team modified their ETD harvester to introduced some sleep time between collection feed requests while also introducing retries for 504 errors.

However the harvest also encounters the following error – 'Connection reset by peer'. We should see if there's evidence in the ALB or UI logs regarding this connection issue and resolve if possible.
```
Exception fetching Merritt file: URLError(ConnectionResetError(104, 'Connection reset by peer'))
Item error: <urlopen error [Errno 104] Connection reset by peer>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by elopatin-uc3** [comment]
Could this be WAF throttling? or UI ALB?

**Comment by elopatin-uc3** [comment]
No longer seeing this issue. Closing
