### ISSUE TITLE
int test all -- timing issue

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1333]
This failed once and then worked on the second run 

```
[ERROR] Tests run: 24, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 207.837 s <<< FAILURE! - in org.cdlib.mrt.ingest.ServiceDriverIT
[ERROR] TestManifestWithRequeue(org.cdlib.mrt.ingest.ServiceDriverIT)  Time elapsed: 17.97 s  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<404>
	at org.cdlib.mrt.ingest.ServiceDriverIT.getContent(ServiceDriverIT.java:97)
	at org.cdlib.mrt.ingest.ServiceDriverIT.getJsonContent(ServiceDriverIT.java:127)
	at org.cdlib.mrt.ingest.ServiceDriverIT.TestManifestWithRequeue(ServiceDriverIT.java:538)
```

**Comment by elopatin-uc3** [comment]
@terrywbrady Can this be closed?
