### ISSUE TITLE
[Ingest] Stack trace in Ingest logs

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1342]
A stack trace in the Ingest logs recently appeared related to Zookeeper.
Here is the trace from Ingest, showing that the request is an Ingest queue state.
I tried to recreate the trace with invalid queue request, but was unable.

For now, just monitor.  It does not affect submissions.

Request:   Path("/queue/{queue}")

Trace: 
java.io.StreamCorruptedException: invalid stream header: 3C3F786D
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:937)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:395)
        at org.cdlib.mrt.ingest.QueueManager.getQueueState(QueueManager.java:225)
        at org.cdlib.mrt.ingest.service.IngestService.getQueueState(IngestService.java:294)
        at org.cdlib.mrt.ingest.app.jersey.admin.JerseyAdmin.getQueueState(JerseyAdmin.java:345)

Zookeeper server logs show:
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:49974, session = 0x100000dfee36d9c

**Comment by terrywbrady** [comment]
Archive for now.

**Comment by elopatin-uc3** [comment]
Mark found the cause for this stack trace: e.g. asking for inventory queue information by using the call for the ingest queue.
Specific requests are needed for ingest, inventory and access queues.

**Comment by mreyescdl** [comment]
Caught stack traces for all 3 query queue APIs.  Log a meaningful message to Ingest.
Some stack traces still exist in the core lib code.

**Comment by mreyescdl** [comment]
Deployed to production
