### ISSUE TITLE
Docker testing upload failure

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1419]
```
[25268e9d-cad4-4f93-91a0-2667199791f8] Started POST "/object/upload" for 172.31.49.209 at 2023-04-04 09:53:01 -0700
[25268e9d-cad4-4f93-91a0-2667199791f8] Processing by ObjectController#upload as HTML
[25268e9d-cad4-4f93-91a0-2667199791f8]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "upload-limit"=>"1000000000", "upload-limit-message"=>"1 GB", "file"=>#<ActionDispatch::Http::UploadedFile:0x00007f37549f4880 @tempfile=#<Tempfile:/tmp/RackMultipart20230404-1-6yc8pf.ico>, @original_filename="cliché.ico", @content_type="image/vnd.microsoft.icon", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"cliche\xCC\x81.ico\"\r\nContent-Type: image/vnd.microsoft.icon\r\n">, "title"=>"test", "author"=>"", "date"=>"", "local_id"=>"", "primary_id"=>"", "group"=>"merritt_demo", "commit"=>"Submit"}
[25268e9d-cad4-4f93-91a0-2667199791f8] Completed 500 Internal Server Error in 127ms (ActiveRecord: 0.0ms | Allocations: 2395)
[25268e9d-cad4-4f93-91a0-2667199791f8]   
[25268e9d-cad4-4f93-91a0-2667199791f8] SocketError (getaddrinfo: Name or service not known (nil-uri-given:80)):
[25268e9d-cad4-4f93-91a0-2667199791f8]   
[25268e9d-cad4-4f93-91a0-2667199791f8] app/lib/http_mixin.rb:21:in `block in http_post'
[25268e9d-cad4-4f93-91a0-2667199791f8] app/lib/http_mixin.rb:20:in `loop'
[25268e9d-cad4-4f93-91a0-2667199791f8] app/lib/http_mixin.rb:20:in `http_post'
[25268e9d-cad4-4f93-91a0-2667199791f8] app/lib/ingest_mixin.rb:121:in `post_upload'
[25268e9d-cad4-4f93-91a0-2667199791f8] app/controllers/object_controller.rb:83:in `upload'
```

**Comment by terrywbrady** [comment]
Closing... I introduced a bug in the app_config.yml file
