### ISSUE TITLE
Intermittent 401 encountered by eSchol ETD harvester

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1435]
As of 4/12 the harvester occasionally errors out with a 401:
```
Harvesting UCLA ETDS.
HTTP error 'HTTP Error 504: Gateway Time-out' - will retry 2 more time(s).
Unhandled exception:
Traceback (most recent call last):
  File "/apps/eschol/erep/xtf/control/tasks/harvestBase.py", line 127, in main
    self.doHarvest()
  File "erep/xtf/control/tasks/merrittHarvest.py", line 353, in doHarvest
    self.harvestCollection("ucla", "[https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5ww7fz0"](https://merritt.cdlib.org/object/recent.atom?collection=ark:/13030/m5ww7fz0%22))
  File "erep/xtf/control/tasks/merrittHarvest.py", line 305, in harvestCollection
    feedData = xmlutil.stringToXML(self.openURL(feedLink).read())
  File "/apps/eschol/erep/xtf/control/tasks/task.py", line 102, in openURL
    ret = self.urlOpener.open(req)
  File "/usr/lib64/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by elopatin-uc3** [comment]
This occurred again on May 8 and 9.

**Comment by elopatin-uc3** [comment]
Is eSchol authentication session-based?

**Comment by elopatin-uc3** [comment]
First observation of 401 was on April 12th.

**Comment by terrywbrady** [comment]
UI logs
```
[098180eb-b9ce-4435-99e4-8ec0dd309342] Started GET "/object/recent.atom?collection=ark:/13030/m5542sfd&page=9&per_page=500" for 54.244.52.85 at 2023-05-15 10:06:54 -0700
[098180eb-b9ce-4435-99e4-8ec0dd309342] Processing by ObjectController#recent as ATOM
[098180eb-b9ce-4435-99e4-8ec0dd309342]   Parameters: {"collection"=>"ark:/13030/m5542sfd", "page"=>"9", "per_page"=>"500"}
[098180eb-b9ce-4435-99e4-8ec0dd309342]   Rendering text template
[098180eb-b9ce-4435-99e4-8ec0dd309342]   Rendered text template (Duration: 0.0ms | Allocations: 1)
[098180eb-b9ce-4435-99e4-8ec0dd309342] Filter chain halted as :require_named_user_or_401 rendered or redirected
[098180eb-b9ce-4435-99e4-8ec0dd309342] Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms | Allocations: 298)
```

WAF logs in open search seems to show that basic auth credentials were provided.  

TODO: look at ALB logs
