### ISSUE TITLE
[INGEST]  Stack trace when updating a new object

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#1458]
We introduced a stack trace with the Jersey upgrade code for when an update submission is requested for an object that has not yet been created.  Dryad uses this as their submission method.
Although it is an ugly looking trace (see below), it is in effect harmless.

Ingest tries to the augment new metadata with older versions so no data is overwritten.  It does this my using the previous versions ERC data via the "mrt-erc.txt" file.
When upgrading off of the Jersey http client code, I changed the mechanics of grabbing this data.  In doing this I introduced a condition where an exception is thrown. 

This is an easy fix and will piggy back off of the Queue redesign work for deployment.

```
[debug] StorageUtil:  storage URL: http://storage.cdlib.org:35121/content/3041/ark%3A%2F13030%2Fm5tv2f9m/0/system%2Fmrt-erc.txt
[debug] StorageUtil:  response code 404
org.cdlib.mrt.utility.FileUtil-string2File:383 INVALID_OR_MISSING_PARM[Program required parm is missing or invalid] FileUtil: buildDflatInfoFile - bad argument
        at org.cdlib.mrt.utility.FileUtil.string2File(FileUtil.java:383)
        at org.cdlib.mrt.ingest.utility.StorageUtil.getStorageFile(StorageUtil.java:105)
        at org.cdlib.mrt.ingest.handlers.HandlerMinter.handle(HandlerMinter.java:191)
        at org.cdlib.mrt.ingest.handlers.HandlerMinter.handle(HandlerMinter.java:65)
        at org.cdlib.mrt.ingest.IngestManager.submit(IngestManager.java:617)
        at org.cdlib.mrt.ingest.service.IngestService.submit(IngestService.java:82)
        at org.cdlib.mrt.ingest.consumer.ConsumeData.run(Consumer.java:617)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by mreyescdl** [comment]
Fixed in branch consolidateIngestQueues
- java/org/cdlib/mrt/ingest/utility/StorageUtil.java

**Comment by mreyescdl** [comment]
To do:  Determine if updating a new object (versus "submit") is tested in the integration test.
