### ISSUE TITLE
Fix DEV Docker Stack access to S3 DEV buckets

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1533]
## Error
```
CANCloudService: Run Exception: org.cdlib.mrt.s3.aws.AWSS3Cloud-awsHandleException:1663 USER_NOT_AUTHENTICATED[User not authenticated] AWS fails authentication
!!!!Exception:org.cdlib.mrt.s3.aws.AWSS3Cloud-awsHandleException:1663 USER_NOT_AUTHENTICATED[User not authenticated] AWS fails authenticationTrace:org.cdlib.mrt.s3.aws.AWSS3Cloud-awsHandleException:1663 USER_NOT_AUTHENTICATED[User not authenticated] AWS fails authentication
        at org.cdlib.mrt.s3.aws.AWSS3Cloud.awsHandleException(AWSS3Cloud.java:1663)
        at org.cdlib.mrt.s3.aws.AWSS3Cloud.getObjectMeta(AWSS3Cloud.java:1173)
        at org.cdlib.mrt.s3.aws.AWSS3Cloud.awsGet(AWSS3Cloud.java:672)
        at org.cdlib.mrt.s3.aws.AWSS3Cloud.getObject(AWSS3Cloud.java:1076)
        at org.cdlib.mrt.s3.aws.AWSS3Cloud.getManifest(AWSS3Cloud.java:1412)
        at org.cdlib.mrt.s3.aws.AWSS3Cloud.getManifest(AWSS3Cloud.java:1386)
        at 
```

## temporary work around
```
diff --git a/mrt-services/docker-dev.yml b/mrt-services/docker-dev.yml
index ca4303e..8ab9863 100644
--- a/mrt-services/docker-dev.yml
+++ b/mrt-services/docker-dev.yml
@@ -18,12 +18,12 @@ services:
   store:
     environment:
       SSM_SKIP_RESOLUTION: 
-      NODE_TABLE: nodes-dev
+      #NODE_TABLE: nodes-dev
       SSM_ROOT_PATH: /uc3/mrt/dev/
-      MERRITT_STORE_INFO: store-info-dev-docker
-  ingest:
-    volumes:
-    - ./ingest/profiles-dev/:/tdr/ingest/profiles/
+      #MERRITT_STORE_INFO: store-info-dev-docker
+  #ingest:
+    #volumes:
+    #- ./ingest/profiles-dev/:/tdr/ingest/profiles/
   # The following setting will connect to the DEV database
   # But, the contents of the cloud nodes will not be compatible with this stack
   audit:
```

**Comment by elopatin-uc3** [comment]
May have been affected by the TLS 1.2 tests David and Joe ran a while back.

**Comment by terrywbrady** [comment]
@dloy and Joe restored access to this bucket. This is now working.
