### ISSUE TITLE
OpenSSL error during LDAP authentication

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#157]
Received an error when trying to authenticate on a download operation.  See details below:

A Net::LDAP::Error occurred in file#download:

  SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read finished A
  lib/user_ldap.rb:44:in `authenticate'

-------------------------------
Request:
-------------------------------

  * URL        : http://merritt.cdlib.org/d/ark%3A%2F13030%2Fm51n7z5q/3/producer%2FTsay_uci_0030D_10629_DATA.xml
  * HTTP Method: GET
  * IP address : 172.30.22.60
  * Parameters : {"controller"=>"file", "action"=>"download", "object"=>"ark:/13030/m51n7z5q", "version"=>"3", "file"=>"producer/Tsay_uci_0030D_10629_DATA.xml"}
  * Timestamp  : 2019-08-13 17:07:32 UTC
  * Server : uc3-mrtui02-prd
  * Rails root : /apps/dpr2/apps/ui/releases/20190425211949
  * Process: 9195

-------------------------------
Environment:
-------------------------------
* HTTP_HOST                                      : ui02-aws.cdlib.org:26181
  * HTTP_USER_AGENT                                : CDLRepositoryHarvester/0.4

-------------------------------
Backtrace:
-------------------------------

  lib/user_ldap.rb:44:in `authenticate'
  app/models/user.rb:73:in `valid_ldap_credentials?'
  app/models/user.rb:83:in `from_auth_header'
  app/controllers/application_controller.rb:88:in `current_user'
  app/controllers/application_controller.rb:95:in `current_uid'
  app/controllers/application_controller.rb:106:in `require_user'

 - [ ] look server side to see if anything is obvious

**Comment by elopatin-uc3** [comment]
Closing as obsolete.
