### ISSUE TITLE
Next UI database error - add retry logic

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1617]
```
[6ee44dce-5368-4a3b-b6de-79d63100f049]   
[6ee44dce-5368-4a3b-b6de-79d63100f049] ActiveRecord::StatementInvalid (Mysql2::Error: Commands out of sync; you can't run this command now):
[6ee44dce-5368-4a3b-b6de-79d63100f049]   
[6ee44dce-5368-4a3b-b6de-79d63100f049] app/models/inv_object.rb:60:in `dua_exists?'
[6ee44dce-5368-4a3b-b6de-79d63100f049] app/lib/dua_mixin.rb:25:in `check_dua'
[6ee44dce-5368-4a3b-b6de-79d63100f049] app/controllers/file_controller.rb:72:in `check_version'
```

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-doc/issues/1629
