### ISSUE TITLE
New token 500 status errors - access

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1716]
## Problem
Access/storage was fixed to eliminate 404 errors that occurred as a result of content being deleted and then rewritten between async processes. The fix used S3 replace functionality. Instead of write object, delete object - write object, replace object was used.

An unexpected result of this process is that S3 may not complete writing an object before the content is returned to another thread. The object may be truncated. 

This truncation of a JSON file can return invalid JSON - terminating characters are missing.

The current fix, will use retry logic to confirm completion of the JSON response.

## Exception
~~~
[info] START: consuming queue data:{"status":201,"token":"a4cd1716-a498-48ce-aa4e-4038669dfb98","cloud-content-byte":224939,"delivery-node":7001}
[info] ConsumerDaemon: No data in queue to process
ConsumerDaemon: Waiting for polling interval(seconds): 15
org.json.JSONException: Expected a ',' or ']' at 556 [character 557 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:432)
        at org.json.JSONArray.<init>(JSONArray.java:130)
        at org.json.JSONTokener.nextValue(JSONTokener.java:365)
        at org.json.JSONObject.<init>(JSONObject.java:208)
        at org.json.JSONObject.<init>(JSONObject.java:310)
        at org.cdlib.mrt.store.tools.JSONNull.<init>(JSONNull.java:50)
        at org.cdlib.mrt.store.TokenStatus.getTokenStatusFromJson(TokenStatus.java:622)
        at org.cdlib.mrt.store.action.TokenManager.getCloudToken(TokenManager.java:812)
        at org.cdlib.mrt.store.action.TokenManager.getCloudToken(TokenManager.java:772)
        at org.cdlib.mrt.store.app.jersey.JerseyBase.doPresignAsynchObject(JerseyBase.java:1822)
        at org.cdlib.mrt.store.app.jersey.store.JerseyStorage.getPresignAsynchObject(JerseyStorage.java:1132)
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces:
~~~

**Comment by dloy** [comment]
Retry has eliminated most of these. Caused by one thread partially writing content that another thread is reading
