### ISSUE TITLE
Collection profile creation process doesn't work due to jquery error

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1862]
Attempting to generate an Admin profile results in the following jquery error in the console:
```
jquery.min.js:2 Uncaught Error: no such method 'select' for tabs widget instance
    at Function.error (jquery.min.js:2:2741)
    at HTMLDivElement.<anonymous> (jquery-ui.min.js:6:2067)
    at Function.each (jquery.min.js:2:3129)
    at ce.fn.init.each (jquery.min.js:2:1594)
    at V.fn.<computed> [as tabs] (jquery-ui.min.js:6:1951)
    at Object.success (collProfile.html:1846:10)
    at c (jquery.min.js:2:25304)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:26053)
    at l (jquery.min.js:2:77782)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:80265)
```

This is preceded by:
```
Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

Steps to reproduce (Stage or Prod):
01 Visit https://merritt-colladmin.cdlib.org/web/collProfile.html
02 Type in a test mnemonic
03 Choose a collection owner
04 Add a test collection title
05 Enter an email address in the End-user Notifications field
06 Click the Create Profile button

Result:
- No collection profile returned from Ingest. jquery error appears in concole

**Comment by terrywbrady** [comment]
This is the likely cause.  I will test a fix.  https://stackoverflow.com/a/15304028/3846548

**Comment by elopatin-uc3** [comment]
Thanks for having a look

**Comment by elopatin-uc3** [comment]
Working as expected now. Tested in prod.

**Comment by terrywbrady** [comment]
https://github.com/CDLUC3/mrt-admin-lambda/commit/137c9ade6903a5d342ac2d235938eae7bc324cc0
