### ISSUE TITLE
ETDs: Encoding error has occurred while attempting to parse an ETD zip

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#1919]
```
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 334, in <module>
    main()
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 322, in main
    (merritt_pm_list, pq_md_list) = extract_metadata(hostenv)
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 191, in extract_metadata
    dom = ET.fromstring(pqstring)
  File "src/lxml/etree.pyx", line 3222, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 90
lxml.etree.XMLSyntaxError: Char 0xFFFE out of allowed range, line 90, column 174
```

**Comment by elopatin-uc3** [comment]
160+ ETDs are waiting to be processed in the zipfiles directory

**Comment by elopatin-uc3** [comment]
Removed problematic character from ETD XML abstract.

Now running getetds.py to ingest all waiting ETDs in the zipfiles directory.

**Comment by elopatin-uc3** [comment]
Script run completed successfully
