### ISSUE TITLE
UI 500: Ad-hoc 500 errors in Merritt UI

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1965]
## recent.atom
```
"_source": {
    "json": {
      "view": 0,
      "allocations": 53110,
      "action": "recent",
      "error": "ActionView::Template::Error: Mysql2::Error: Unknown MySQL error",
      "db": 89.83,
      "method": "GET",
      "status": 500,
      "time": 1803627.205242145,
      "message": "[500] GET /object/recent.atom (ObjectController#recent)",
      "@timestamp": "2024-06-25T19:34:22.934Z",
      "duration": 326.85,
      "controller": "ObjectController",
      "format": "atom",
      "@version": "1",
      "path": "/object/recent.atom"
    },
```

```
[31135a14-00c1-4ae9-bb8f-e35badba4fb7] Started GET "/api/presign-file/ark%253A%252F13030%252Fqt6sj778f9/0/producer%252Fmeta%252Fqt6sj778f9.meta.xml
" for 54.244.52.85 at 2024-06-21 18:19:00 -0700
[31135a14-00c1-4ae9-bb8f-e35badba4fb7] Processing by FileController#presign as XML
[31135a14-00c1-4ae9-bb8f-e35badba4fb7]   Parameters: {"object"=>"ark%3A%2F13030%2Fqt6sj778f9", "version"=>"0", "file"=>"producer%2Fmeta%2Fqt6sj778f
9.meta.xml"}
[31135a14-00c1-4ae9-bb8f-e35badba4fb7]   ESC[1mESC[36mInvObject Load (0.2ms)ESC[0m  ESC[1mESC[34mSELECT `inv_objects`.* FROM `inv_objects` WHERE `i
nv_objects`.`ark` = 'ark:/13030/qt6sj778f9' LIMIT 1ESC[0m
[31135a14-00c1-4ae9-bb8f-e35badba4fb7] Completed 500 Internal Server Error in 50ms (ActiveRecord: 0.2ms | Allocations: 2492)
[31135a14-00c1-4ae9-bb8f-e35badba4fb7]   
[31135a14-00c1-4ae9-bb8f-e35badba4fb7] ActiveRecord::StatementInvalid (Mysql2::Error: Unknown MySQL error):
[31135a14-00c1-4ae9-bb8f-e35badba4fb7]   
[31135a14-00c1-4ae9-bb8f-e35badba4fb7] app/controllers/application_controller.rb:70:in `redirect_to_latest_version'
[0
```

```
  "json": {
      "duration": 1935.15,
      "view": 0,
      "action": "recent",
      "status": 500,
      "@version": "1",
      "method": "GET",
      "time": 672473.659447071,
      "message": "[500] GET /object/recent.atom (ObjectController#recent)",
      "allocations": 709385,
      "db": 864.24,
      "@timestamp": "2024-06-12T17:33:40.912Z",
      "controller": "ObjectController",
      "format": "atom",
      "path": "/object/recent.atom",
      "error": "ActionView::Template::Error: Mysql2::Error: Commands out of sync; you can't run this command now"
    },

```

```
[b7170576-d2d7-43bd-b081-f3eef095b63f]   ESC[1mESC[36mInvFile Load (4.0ms)ESC[0m  ESC[1mESC[34mSELECT `inv_files`.* FROM `inv_files` WHERE `inv_fil
es`.`inv_version_id` = 3185135ESC[0m
[b7170576-d2d7-43bd-b081-f3eef095b63f]   Rendered object/recent.atom.builder (Duration: 1784.3ms | Allocations: 704666)
[b7170576-d2d7-43bd-b081-f3eef095b63f] Completed 500 Internal Server Error in 1935ms (ActiveRecord: 864.2ms | Allocations: 709371)
[b7170576-d2d7-43bd-b081-f3eef095b63f]   
[b7170576-d2d7-43bd-b081-f3eef095b63f] ActionView::Template::Error (Mysql2::Error: Commands out of sync; you can't run this command now):
[b7170576-d2d7-43bd-b081-f3eef095b63f]     68:       xml.tag!('updated', obj.modified.to_formatted_s(:w3cdtf))
[b7170576-d2d7-43bd-b081-f3eef095b63f]     69:       xml.tag!('published', obj.created.to_formatted_s(:w3cdtf)) unless obj.created.blank?
[b7170576-d2d7-43bd-b081-f3eef095b63f]     70:       current_version = obj.current_version
[b7170576-d2d7-43bd-b081-f3eef095b63f]     71:       current_version.inv_files.each do |file|
[b7170576-d2d7-43bd-b081-f3eef095b63f]     72:         xml.tag!('link',
[b7170576-d2d7-43bd-b081-f3eef095b63f]     73:                  'href' => presigned_link_uri(obj, current_version, file),
[b7170576-d2d7-43bd-b081-f3eef095b63f]     74:                  'rel' => 'http://purl.org/dc/terms/hasPart',
[b7170576-d2d7-43bd-b081-f3eef095b63f]   
[b7170576-d2d7-43bd-b081-f3eef095b63f] app/views/object/recent.atom.builder:71
[b7170576-d2d7-43bd-b081-f3eef095b63f] app/views/object/recent.atom.builder:43
[b7170576-d2d7-43bd-b081-f3eef095b63f] app/views/object/recent.atom.builder:42
[b7170576-d2d7-43bd-b081-f3eef095b63f] app/views/object/recent.atom.builder:3
[d88241
```

## presigned_file

```
"json": {
      "duration": 114.5,
      "view": 0,
      "action": "index",
      "@version": "1",
      "status": 500,
      "time": 1283469.225235531,
      "method": "GET",
      "message": "[500] GET /m/ark%3A%2F28722%2Fk2br8vk09 (ObjectController#index)",
      "allocations": 7223,
      "db": 10,
      "@timestamp": "2024-06-19T18:51:56.652Z",
      "controller": "ObjectController",
      "format": "*/*",
      "path": "/m/ark%3A%2F28722%2Fk2br8vk09",
      "error": "ActionView::Template::Error: Mysql2::Error: Commands out of sync; you can't run this command now"
    },
```

```
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]   Rendered object/_details_display.html.erb (Duration: 4.5ms | Allocations: 1801)
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]   Rendered object/index.html.erb within layouts/application (Duration: 20.4ms | Allocations: 3646)
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]   Rendered layout layouts/application.html.erb (Duration: 20.5ms | Allocations: 3689)
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba] Completed 500 Internal Server Error in 114ms (ActiveRecord: 10.0ms | Allocations: 7209)
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]   
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba] ActionView::Template::Error (Mysql2::Error: Commands out of sync; you can't run this command now):
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]     34:   </tr>
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]     35:   <tr class="object_size">
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]     36:     <th>object size:</th>
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]     37:     <td><%= number_to_storage_size(details_display.size) %></td>
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]     38:   </tr>
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]     39:   <tr class="object_versions">
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]     40:     <th>total versions:</th>
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba]   
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba] app/models/inv_object.rb:64:in `size'
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba] app/views/object/_details_display.html.erb:37
[32b138bb-5ad5-4d8c-abb0-6b9d037162ba] app/views/object/index.html.erb:24
[6489
```

**Comment by elopatin-uc3** [comment]
Closing per other more recent UI 500 error investigations.
