### ISSUE TITLE
UI 500: Set of 500 errors in Merritt UI 6/21-6/23, MerrittRetryMixin::RetryException:

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#1966]
## Errors seem to be resolved after patching

![Image](https://github.com/CDLUC3/mrt-doc/assets/1111057/0ea7b3d0-052f-46b9-8bd0-aa4f4799943e)

## Where/When did the error occur?

- UI02: 6/23 10:37 - 6/23 10:48
- UI03: 6/21 11:03 - 6/22 02:50

## UI03

```
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218] Started GET "/api/presign-file/ark%253A%252F13030%252Fm5qz2fs0/5/producer%252FRice_uci_0030D_12238_DATA.xml" for 54.244.52.85 at 2024-06-23 10:38:14 -0700
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218] Processing by FileController#presign as XML
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   Parameters: {"object"=>"ark%3A%2F13030%2Fm5qz2fs0", "version"=>"5", "file"=>"producer%2FRice_uci_0030D_12238_DATA.xml"}
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   InvFile Load (0.1ms)  SELECT `inv_files`.* FROM `inv_files` INNER JOIN `inv_versions` ON `inv_versions`.`id` = `inv_files`.`inv_version_id` INNER JOIN `inv_objects` ON `inv_objects`.`id` = `inv_files`.`inv_object_id` WHERE (inv_objects.ark = 'ark:/13030/m5qz2fs0') AND (inv_versions.number = '5') AND (inv_files.pathname = 'producer/Rice_uci_0030D_12238_DATA.xml') ORDER BY `inv_files`.`id` ASC LIMIT 1
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   InvVersion Load (0.1ms)  SELECT `inv_versions`.* FROM `inv_versions` WHERE `inv_versions`.`id` = 3184739 LIMIT 1
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   InvObject Load (0.1ms)  SELECT `inv_objects`.* FROM `inv_objects` WHERE `inv_objects`.`id` = 25615 LIMIT 1
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   InvCollection Load (0.0ms)  SELECT `inv_collections`.* FROM `inv_collections` INNER JOIN `inv_collections_inv_objects` ON `inv_collections`.`id` = `inv_collections_inv_objects`.`inv_collection_id` WHERE `inv_collections_inv_objects`.`inv_object_id` = 39812757 ORDER BY `inv_collections`.`id` ASC LIMIT 1
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   CACHE InvCollection Load (0.0ms)  SELECT `inv_collections`.* FROM `inv_collections` INNER JOIN `inv_collections_inv_objects` ON `inv_collections`.`id` = `inv_collections_inv_objects`.`inv_collection_id` WHERE `inv_collections_inv_objects`.`inv_object_id` = 39812757 ORDER BY `inv_collections`.`id` ASC LIMIT 1
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   CACHE InvCollection Load (0.0ms)  SELECT `inv_collections`.* FROM `inv_collections` INNER JOIN `inv_collections_inv_objects` ON `inv_collections`.`id` = `inv_collections_inv_objects`.`inv_collection_id` WHERE `inv_collections_inv_objects`.`inv_object_id` = 39812757 ORDER BY `inv_collections`.`id` ASC LIMIT 1
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   CACHE InvCollection Load (0.0ms)  SELECT `inv_collections`.* FROM `inv_collections` INNER JOIN `inv_collections_inv_objects` ON `inv_collections`.`id` = `inv_collections_inv_objects`.`inv_collection_id` WHERE `inv_collections_inv_objects`.`inv_object_id` = 39812757 ORDER BY `inv_collections`.`id` ASC LIMIT 1
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218] Completed 500 Internal Server Error in 3038ms (ActiveRecord: 0.3ms | Allocations: 4435)
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218] MerrittRetryMixin::RetryException (undefined method `group' for nil:NilClass):
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218]   
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218] app/lib/merritt_retry_mixin.rb:18:in `rescue in merritt_retry_block'
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218] app/lib/merritt_retry_mixin.rb:14:in `merritt_retry_block'
[aea27c27-5251-4bfa-b2a5-0a84f3aa9218] app/controllers/file_controller.rb:51:in `check_download'
```

## UI02

```
[09529043-5fa9-4b14-9b0e-556683d14b4f] Started GET "/m/ark%3A%2F28722%2Fk2vm43r82" for 52.35.63.194 at 2024-06-21 18:06:27 -0700
[09529043-5fa9-4b14-9b0e-556683d14b4f] Processing by ObjectController#index as */*
[09529043-5fa9-4b14-9b0e-556683d14b4f]   Parameters: {"object"=>"ark:/28722/k2vm43r82"}
[09529043-5fa9-4b14-9b0e-556683d14b4f]   InvObject Load (0.1ms)  SELECT `inv_objects`.* FROM `inv_objects` WHERE (ark = 'ark:/28722/k2vm43r82') ORDER BY `inv_objects`.`id` ASC LIMIT 1
[09529043-5fa9-4b14-9b0e-556683d14b4f]   InvCollectionsInvObject Load (0.1ms)  SELECT `inv_collections_inv_objects`.* FROM `inv_collections_inv_objects` WHERE `inv_collections_inv_objects`.`inv_object_id` = 4607023
[09529043-5fa9-4b14-9b0e-556683d14b4f]   CACHE InvObject Load (0.0ms)  SELECT `inv_objects`.* FROM `inv_objects` WHERE (ark = 'ark:/28722/k2vm43r82') ORDER BY `inv_objects`.`id` ASC LIMIT 1
[09529043-5fa9-4b14-9b0e-556683d14b4f]   CACHE InvCollectionsInvObject Load (0.0ms)  SELECT `inv_collections_inv_objects`.* FROM `inv_collections_inv_objects` WHERE `inv_collections_inv_objects`.`inv_object_id` = 4607023
[09529043-5fa9-4b14-9b0e-556683d14b4f]   CACHE InvObject Load (0.0ms)  SELECT `inv_objects`.* FROM `inv_objects` WHERE (ark = 'ark:/28722/k2vm43r82') ORDER BY `inv_objects`.`id` ASC LIMIT 1
[09529043-5fa9-4b14-9b0e-556683d14b4f]   CACHE InvCollectionsInvObject Load (0.0ms)  SELECT `inv_collections_inv_objects`.* FROM `inv_collections_inv_objects` WHERE `inv_collections_inv_objects`.`inv_object_id` = 4607023
[09529043-5fa9-4b14-9b0e-556683d14b4f]   CACHE InvObject Load (0.0ms)  SELECT `inv_objects`.* FROM `inv_objects` WHERE (ark = 'ark:/28722/k2vm43r82') ORDER BY `inv_objects`.`id` ASC LIMIT 1
[09529043-5fa9-4b14-9b0e-556683d14b4f]   CACHE InvCollectionsInvObject Load (0.0ms)  SELECT `inv_collections_inv_objects`.* FROM `inv_collections_inv_objects` WHERE `inv_collections_inv_objects`.`inv_object_id` = 4607023
[09529043-5fa9-4b14-9b0e-556683d14b4f] Completed 500 Internal Server Error in 3007ms (ActiveRecord: 0.2ms | Allocations: 6797)
[09529043-5fa9-4b14-9b0e-556683d14b4f]   
[09529043-5fa9-4b14-9b0e-556683d14b4f] MerrittRetryMixin::RetryException (missing attribute: inv_object_id):
[09529043-5fa9-4b14-9b0e-556683d14b4f]   
[09529043-5fa9-4b14-9b0e-556683d14b4f] app/lib/merritt_retry_mixin.rb:18:in `rescue in merritt_retry_block'
[09529043-5fa9-4b14-9b0e-556683d14b4f] app/lib/merritt_retry_mixin.rb:14:in `merritt_retry_block'
[09529043-5fa9-4b14-9b0e-556683d14b4f] app/controllers/object_controller.rb:30:in `load_object'
```

**Comment by elopatin-uc3** [comment]
Closing per other more recent UI 500 error investigations.
