### ISSUE TITLE
[Ingest]  Bug when unzipping container with bad content

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#2050]
If Container manifest has a bad ZIP file, then failure does not cause exit.
Unzip operation is caught in a loop.

```
[error] + HandlerDisaggregate: error decompressing file: /dpr2/ingest_home/queue/bid-09d2f7d2-145b-46de-bd01-9fdae23981ee/jid-fb919613-6e09-4b2b-8fe4-bc01cd8389de/producer/huskyChicken.zip
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
        at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.cdlib.mrt.ingest.handlers.initialize.HandlerDisaggregate.decompress(HandlerDisaggregate.java:305)
        at org.cdlib.mrt.ingest.handlers.initialize.HandlerDisaggregate.handle(HandlerDisaggregate.java:109)
        at org.cdlib.mrt.ingest.handlers.initialize.HandlerDisaggregate.handle(HandlerDisaggregate.java:65)
        at org.cdlib.mrt.ingest.ProcessManager.submit(ProcessManager.java:516)
        at org.cdlib.mrt.ingest.service.IngestService.submitProcess(IngestService.java:110)
        at org.cdlib.mrt.ingest.consumer.InitializeConsumeData.run(InitializeConsumer.java:549)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mreyescdl** [comment]
ZIP Container had a zip file in its contents.  Perhaps this triggered the error?
Are we trying to unzip a second level?

Removed the second level zip file and submission was processed.
Needs investigation

**Comment by mreyescdl** [comment]
Error occurs when the Zip file inside another Zip file is named the same.  e.g..

Unpacking huskyChicken.zip
- payload.txt
- mrt-erc.txt
- huskyChicken.zip

Ingest unpacks the container in the same directory in which the container lives and thus this condition causes a filename collision.

This is not a bug and consider this ticket completed.
