### ISSUE TITLE
Investigate KeyError blocking deletion of ETD zips

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2079]
After fixing #2074, createmarc.py is throwing a KeyError:
```
Starting createmarc at Tue Oct 22 13:30:01 PDT 2024
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 981, in <module>
    main()
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 976, in main
    delete_working_files(hostenv)
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 408, in delete_working_files
    ok_to_delete = check_if_ok_to_delete(zipfilename, hostenv)
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 368, in check_if_ok_to_delete
    if campus_configs[campusabbr]['create_marc']:
KeyError: 'ucla.....;ucla.etd:PQ'
```

This prevents the script from cleaning up old ETD zips and is resulting in distribution of duplicate MARC records.

**Comment by elopatin-uc3** [comment]
Some local id entries in the ETD database (merritt_ingest table), including the one related to this ETD were found which include strings like: ark:/13030/m5vv336t ; PQETD:ucla23493;ucla.etd:PQ23493

The regex in createmarc.py is not able to handle this extensive string and finds:
ucla23493;ucla.etd:PQ

Instead of the campus abbr it's looking for: ucla

It's interesting to note that the handful of earlier problematic local id records, before we released the queue redesign, were still parsed successfully, because the order of the two local id's were reversed. One of these id's is added via the mrt-erc.txt file that UCLA includes with there submission. While the other is generated by the ETD service.

This can be parsed:
ark:/13030/m5vv336t ; ucla.etd:PQ23493;PQETD:ucla23493

While this can't:
ark:/13030/m5vv336t ; PQETD:ucla23493;ucla.etd:PQ23493

In the first example, "PQETD:" is located and only the adjacent "ucla" string is grabbed. In the second example, as noted above, the following string is ascertained, "ucla23493;ucla.etd:PQ" which fails to match the expected campus abbreviation.

**Comment by elopatin-uc3** [comment]
The ETD database with corrected local id records has been uploaded to the ETDs production host. Duplicate xml and mrc files resulting from an incomplete createmarc.py run have been removed. 

I'll monitor the createmarc.py run tomorrow at 1:30 to see if the script can successfully complete and remove zips from the zipfiles directory. Then will need to update the associated regex and deploy a fix for future UCLA deposits.

**Comment by elopatin-uc3** [comment]
Deployed an updated regex at ~3:40PM 10/23

**Comment by elopatin-uc3** [comment]
Now seeing the following KeyError:
```
  File "./createmarc.py", line 368, in check_if_ok_to_delete
    if campus_configs[campusabbr]['create_marc']:
KeyError: 'berkeley1029'
```

**Comment by elopatin-uc3** [comment]
The latest regex change (https://github.com/CDLUC3/uc3-etds/pull/28) resolved this issue. We had missed that the objective of the original one was to actually replace the value from the second group, rather than simply isolating it.
