### ISSUE TITLE
Investigate ETD deposit issue

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#2083]
ETD admin zip 990270 is causing the following error on submission by the ETDs service:

```
2024-10-25 07:30:11,571 ERROR submitting to Merritt: 403 Client Error: Forbidden for url: https://merritt.cdlib.org/object/update/
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 253, in submit_to_merritt
    req.raise_for_status()
  File "/apps/etds/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden for url: https://merritt.cdlib.org/object/update/
```

**Comment by elopatin-uc3** [comment]
Original zip was 107MB due to the PDF. I optimized the PDF and have created a new zip to see if it ingests successfully. No issues found with the accompanying XML file.

**Comment by elopatin-uc3** [comment]
This was being blocked by the WAF, along with another ETD service deposit blocked for the same reason. UCLA also reported a third. TB, AG, EL investigated and modified a WAF rule for two URIs that can only be reached while authenticated.
