### ISSUE TITLE
[Ingest] Investigate Ingest not communicating with Zookeeper after patching

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#2100]
Ingest Stage workers needed a restart after patching cycle to regain ZK communication

Stage Zookeeper uses AL2023 boxes.
Monitor production patching and see if old Zookeeper production workers exhibit same problem.
If so, then it is an issue with Ingest.
If not, then it may be an issue with Zookeeper

**Comment by mreyescdl** [comment]
The following are the type of errors that Ingest worker was issuing
```
15:59:23.943 [main-SendThread(uc3-mrtzk-stg03.cdlib.org:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x2007e4d149c3e2f for server uc3-m
rtzk-stg03.cdlib.org/172.31.14.212:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. 
java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:74)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
```

**Comment by mreyescdl** [comment]
Restarted all Stage zookeeper workers (AL2023) and there were no issues with Ingest communications.
Considered the issue closed, but will monitor next patching cycle.

Let's remove old stage Zookeeper workers and  move production workers to AL2023
