### ISSUE TITLE
[Ingest] Zookeeper Job status is null

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#2121]
Error while setting Job status to success()
```
job.setStatus(zooKeeper, job.status().success(), "Success");
```

Stack trace
```
org.cdlib.mrt.zk.MerrittStateError: Status cannot be set to null
        at org.cdlib.mrt.zk.QueueItem.setStatus(QueueItem.java:250)
        at org.cdlib.mrt.ingest.consumer.ProcessConsumeData.run(ProcessConsumer.java:545)
```

Let's try and debug this instead of catching the error and retrying.
If this occurs, then print out as much Job information as possible.

**Comment by mreyescdl** [comment]
Various Zookeeper client side changes have fixed this issue.
Let's close this ticket and reopen later if error reappears

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl , will do.
