### ISSUE TITLE
[Ingest] Zookeeper ingest status is incorrect

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#2125]
While processing a 270 object UCJEPS batch there was a single failure due to an odd state issue.

```
org.cdlib.mrt.zk.MerrittStateError: State change (Downloading->Provisioning) is not allowed
        at org.cdlib.mrt.zk.QueueItem.setStatus(QueueItem.java:255)
        at org.cdlib.mrt.zk.QueueItem.setStatus(QueueItem.java:245)
        at org.cdlib.mrt.ingest.consumer.EstimateConsumeData.run(EstimateConsumer.java:579)
```

 The Estimate consumer daemon thought it was in a "Downloading" state when it was "Estimating"
I'm not sure if this is a ZK library issue or a client one.

Code segment is shown below
```
            if (jobState.getJobStatus() == JobStatusEnum.COMPLETED) {
                if (DEBUG) System.out.println("[item]: EstimateConsumer Daemon COMPLETED queue data:" + jp.toString() + " --- " + ji.toString());
                job.setStatus(zooKeeper, org.cdlib.mrt.zk.JobState.Provisioning);
```

**Comment by mreyescdl** [comment]
Let's assume that this errant state was caused by the Zookeeper issue seen at https://github.com/CDLUC3/mrt-doc/issues/2129

The mentioned issue has a couple of remedy actions.  If we see this again in the future we can re-open this ticket
