### ISSUE TITLE
[Zookeeper] Server error causing client connection issue

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#2129]
On 12/03 at 02:05:30 uc3-mrtzk-prd05, which was the leader encountered a write error.  This triggered an error on all peers and eventually caused Merritt Ingest client side errors.

Here is the stack trace on worker 05
```
2024-12-03 02:05:38,365 [myid:] - ERROR [Sender-/172.30.5.246:36818:o.a.z.s.q.LearnerHandler@372] - Exception while sending packets in LearnerHandler
java.net.SocketException: Broken pipe (Write failed)
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at org.apache.zookeeper.server.quorum.LearnerHandler.sendPackets(LearnerHandler.java:334)
        at org.apache.zookeeper.server.quorum.LearnerHandler.access$200(LearnerHandler.java:65)
        at org.apache.zookeeper.server.quorum.LearnerHandler$1.run(LearnerHandler.java:751)
```

- Not sure if we need to tune Zookeeper better.  Should we explicitly define the Zookeeper JVM or rely on Java to set correctly.

Lets monitor for now.

**Comment by mreyescdl** [comment]
Another occurrence at 2024-12-15 17:36

This time it happened during an Escholarship submission, which has very large Zookeeper payload data, (up to 50K) as well as unicode data (maybe corrupt)

Submitted 50 Eschol objects to Stage, but did not replicate problem.
Continue to look at client side cause of errors.

Here are stack traces from a) client b) ZK worker c) ZK leader

a)
```
BatchReportConsumerDaemon: Checking for additional tasks -  Current tasks: 0 - Max: 5
17:36:02.322 [http-nio-33121-exec-3-SendThread(uc3-mrtzk-prd03.cdlib.org:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server uc3-mrtzk-prd03.cdlib.org/172.30.42.133:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x0, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
```

b)
```
2024-12-15 17:36:02,004 [myid:] - WARN  [QuorumPeer[myid=3](plain=[0:0:0:0:0:0:0:0]:2181)(secure=disabled):o.a.z.s.q.Follower@128] - Exception when following the leader
java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:96)
        at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:86)
        at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:134)
        at org.apache.zookeeper.server.quorum.Learner.readPacket(Learner.java:228)
        at org.apache.zookeeper.server.quorum.Follower.followLeader(Follower.java:124)
        at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1539)
```

c)
```
2024-12-15 17:36:03,139 [myid:] - ERROR [LearnerHandler-/172.30.13.172:57590:o.a.z.s.q.LearnerHandler@719] - Unexpected exception in LearnerHandler:
java.io.EOFException: null
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:96)
        at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:86)
        at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:134)
        at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:656)
```

**Comment by mreyescdl** [comment]
Another Zookeeper error during an Scholarship submission.
The client side error logs informs that the server closed the connection.
```
14:54:09.367 [pool-8-thread-2-SendThread(uc3-mrtzk-prd03.cdlib.org:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x0 for server uc3-mrtzk-prd03.cdlib.org/172.30.42.
133:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x0, likely server has closed socket
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
```

**Comment by mreyescdl** [comment]
The Zookeeper error (noted above) stems from Worker 4 unable to read data from Worker 3
Lets look at where our 5 Zookeeper workers are locates...

```
uc3-mrtzk-prd01: us-west-2a
uc3-mrtzk-prd02: us-west-2b
uc3-mrtzk-prd03: us-west-2c
uc3-mrtzk-prd04: us-west-2a
uc3-mrtzk-prd05: us-west-2b
```

The workers are distributed across 3 AZs.   This is to increase reliability.
However, when under load (from EScholarship) we are writing large data from leader to workers.
If we have 500 objects, each with a payload of 2K - we have 1MB of data being written across AZs
Noted above, the `jute.maxbuffer` has a default of 1MB

Would it be easier if all Zookeeper nodes were in the same AZ?  Does this propose a realistic risk?
Lets discuss with @ashleygould

**Comment by mreyescdl** [comment]
Running on Zookeeper worker 05 is a logger that will snapshot "srvr" info on all 5 workers every 15 minutes.
Running over the holidays there should be no issues of this logger filling up the application disk space.  I estimate it will at max consume 50M and the capacity is 38G

This info will show:
- Number of connections for each worker
- Latency
- Proposal sizing
- Received/Sent requests

Reminder:  Kill process after holiday break.  It is located at:
`uc3-mrtzk-prd05:/dpr2/tools/srvr`

**Comment by mreyescdl** [comment]
We have seen no server-side Zookeeper errors since moving to version 3.93.
We will upgrade client on 1/21.  

Let's keep this ticket open until after the client software has been error-free for a week.

**Comment by mreyescdl** [comment]
We encountered some BAD state transitions in Stage
```
org.cdlib.mrt.zk.MerrittStateError: State change (Completed->Provisioning) is not allowed
```
This is similar to issue https://github.com/CDLUC3/mrt-doc/issues/2125

Investigating this shows that it was caused by a Zookeeper connectivity issue...
```
09:24:29.575 [Thread-10-SendThread(uc3-mrtzk-stg02.cdlib.org:2181)] WARN  org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 103567ms for session id 0x30000e7e31417df
```

I looked in all 3 Zookeeper server logs but could not see any problems.
Lets just note this incident and see if to reoccurs.

We'll keep this ticket open


Also, @terrywbrady wondered if the State transition issue was due to how Ingest code makes transition.
Here is how the daemons switch states.  I recall that explicit state needed to be specified for the first 2 daemons, which is why they differ from the rest.  It may be worth looking into this if error crops up again.

```
InitializeConsumer.java:              job.setStatus(zooKeeper, org.cdlib.mrt.zk.JobState.Estimating);
EstimateConsumer.java:                job.setStatus(zooKeeper, org.cdlib.mrt.zk.JobState.Provisioning);
ProvisionConsumer.java:               job.setStatus(zooKeeper, job.status().success(), "Success");
DownloadConsumer.java:                job.setStatus(zooKeeper, job.status().success(), "Success");
ProcessConsumer.java:                 job.setStatus(zooKeeper, job.status().success(), "Success");
NotifyConsumer.java:                  job.setStatus(zooKeeper, job.status().success(), "Success");
```

**Comment by terrywbrady** [comment]
@mreyescdl , 

The initial state requires an explicit transition because of the possibility of going to the Held or Estimating state.

Estimating has only one allowed successful state.

This may offer an opportunity to simplify the code.

- Ruby: https://github.com/CDLUC3/mrt-zk/blob/main/states.yml
- Java: https://github.com/CDLUC3/mrt-zk/blob/main/src/main/java/org/cdlib/mrt/zk/JobState.java#L36-L46

Let me know if you would like me to modify the ZK orphan report to catch this error in the future.

**Comment by mreyescdl** [comment]
With ZK client and Server at version 3.9.3, we encountered another server-side error.
This time it was between the Leader and a single worker.  Stack trace is shown below.

It seems that the Sever recovers in a couple of seconds.
A client side fix is to wait a few seconds before issuing a retry.

The following webpage has a lot of good ideas to check into to fix root cause.
https://stackoverflow.com/questions/59693707/zookeeper-not-recovering-after-timeout

```
2025-01-23 21:41:10,107 [myid:] - ERROR [LearnerHandler-/172.30.21.12:37098:o.a.z.s.q.LearnerHandler@720] - Unexpected exception in LearnerHandler:
java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:98)
        at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:86)
        at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:136)
        at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:657)
2025-01-23 21:41:10,128 [myid:] - INFO  [LearnerHandler-/172.30.21.12:37098:o.a.z.s.q.LearnerHandler@1160] - Synchronously closing socket to learner 2.
2025-01-23 21:41:10,209 [myid:] - WARN  [LearnerHandler-/172.30.21.12:37098:o.a.z.s.q.LearnerHandler@736] - ******* GOODBYE /172.30.21.12:37098 ********
```

**Comment by mreyescdl** [comment]
We discussed moving from a t3.small instance type to t3.medium for all Zookeeper workers.  This might address the issue of replicating the large Eschol datasets across network.

Instead of just upgrading without knowing that we fixed the issue, it would be beneficial to replicate error in Stage.

I will take time to replicate the error in Stage by ingest large volumes of Eschol data.

**Comment by mreyescdl** [comment]
I'm going to revert Ingest stage back to version 2.1.9
This will match production and allow for better testing for ZK exception

**Comment by mreyescdl** [comment]
Initial test of large Metadata failed to write this data to Zookeeper queue.  Reason?
Eschol submits data in "mrt-erc.txt" file.   I used the following manifest entry type

```
http://uc3-mrtingest-stg01.cdlib.org:33121/ingestqueue/mrt-integ-tests/data1m_erc.tar |  |  |  |  | data1m_erc.tar |  |  | ERC test suite | Large ERC - 1M payload
```

Ingest will not overwrite metadata provided in manifest.
Solution: remove manifest metadata.

**Comment by mreyescdl** [comment]
Finally able to replicate in Ingest Stage.
Submission size:  3000 large metadata objects triggers the error...

```
Attempting reconnect except it is a SessionExpiredException or SessionTimeoutException.
```

**Comment by mreyescdl** [comment]
- Increased Root disk of ZK workers to 20GB https://github.com/CDLUC3/uc3sys/issues/130

- Added more exception handling for ZK object in Ingest

- Ran test of 4000 large metadata objects to Stage WITHOUT errors.

I would like to see if we can decrease Instance type to original t3.small and achieve the same results.

**Comment by mreyescdl** [comment]
Final load testing results.

First, we are okay to leave Zookeeper workers as t3.small in size.  They perform well under testing.

Test 1:  10K objects with large metadata (50K)  
- 4 objects were picked up twice by the same daemon (different workers) but Ingest logic corrected issue
- All objects completed successfully 

Test 2: 10K objects with small metadata
- 1 object was picked up twice by the same daemon (different workers) but Ingest logic corrected issue
- All objects completed successfully

There still exists a locking issue with the Zookeeper library cause by ZK latency or the library code, but it only surfaces under extreme conditions and is corrected for by additional Ingest logic.

**Comment by elopatin-uc3** [comment]
Good to hear @mreyescdl . Thanks for the extensive testing and additional logic in Ingest.
