### ISSUE TITLE
OOM Heap error 

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#49]
jersey error.  Reproducible.

Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2271)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
        at sun.net.www.http.PosterOutputStream.write(PosterOutputStream.java:78)
        at com.sun.jersey.api.client.CommittingOutputStream.write(CommittingOutputStream.java:90)
        at com.sun.jersey.core.util.ReaderWriter.writeTo(ReaderWriter.java:115)
        at com.sun.jersey.core.provider.AbstractMessageReaderWriterProvider.writeTo(AbstractMessageReaderWriterProvider.java:76)
        at com.sun.jersey.core.impl.provider.entity.FileProvider.writeTo(FileProvider.java:103)
        at com.sun.jersey.core.impl.provider.entity.FileProvider.writeTo(FileProvider.java:64)
        at com.sun.jersey.multipart.impl.MultiPartWriter.writeTo(MultiPartWriter.java:220)
        at com.sun.jersey.multipart.impl.MultiPartWriter.writeTo(MultiPartWriter.java:73)
        at com.sun.jersey.api.client.RequestWriter.writeRequestEntity(RequestWriter.java:300)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:217)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570)
        at org.cdlib.mrt.ingest.handlers.HandlerDataONE.handle(HandlerDataONE.java:357)
        at org.cdlib.mrt.ingest.handlers.HandlerDataONE.handle(HandlerDataONE.java:111)
        at org.cdlib.mrt.ingest.IngestManager.submit(IngestManager.java:617)
        at org.cdlib.mrt.ingest.service.IngestService.submit(IngestService.java:76)
        at org.cdlib.mrt.ingest.consumer.ConsumeData.run(Consumer.java:602)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)

 - [ ]

**Comment by elopatin-uc3** [comment]
Data file is located on Ingest01:/dpr2/ingest_home/queue/bid-79c6f190-3ccb-4dab-8bd5-158dcdb1d67d/jid-887c5175-b323-4285-ada1-b136f066080d/producer/SampleMRIData.zip
 (Mark Reyes - Mar 2, 2018)
