### ISSUE TITLE
Sword Service - Explore issue with % file encoding

### ISSUE THREAD

**Issue by terrywbrady** [CDLUC3/mrt-doc#533]
Cannot load a file with a name containing " %AF" from dryad-stg.cdlib.org.

I have fixed this issue (on stage) in the UI, but I wonder if a similar issue exists in the Sword service.

## Dryad Container Error

```
ArgumentError (invalid byte sequence in UTF-8):
  
zaru (0.3.0) lib/zaru.rb:21:in `gsub'
zaru (0.3.0) lib/zaru.rb:21:in `normalize'
zaru (0.3.0) lib/zaru.rb:33:in `sanitize'
zaru (0.3.0) lib/zaru.rb:40:in `truncate'
zaru (0.3.0) lib/zaru.rb:44:in `to_s'
zaru (0.3.0) lib/zaru.rb:49:in `sanitize!'
stash/stash_engine/app/models/stash_engine/file_upload.rb:175:in `sanitize_file_name'
stash/stash_engine/app/controllers/stash_engine/file_uploads_controller.rb:153:in `sanitize_filename'
stash/stash_engine/app/controllers/stash_engine/file_uploads_controller.rb:108:in `set_create_prerequisites'
activesupport (5.2.4.4) lib/active_support/callbacks.rb:426:in `block in make_lambda'

```

**Comment by terrywbrady** [comment]
Closing... no error reported in sword.
