### ISSUE TITLE
MARC records have not been generated since 1/15/21

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#585]
The daily createmarc.py script has been erroring out daily since January 15th. We are no longer sending out records or archiving them in Merritt.

Example error:
```
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 975, in <module>
    main()
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 957, in main
    convert_marc_to_xml(hostenv)
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 475, in convert_marc_to_xml
    for record in reader:
  File "/apps/etds/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)
  File "/apps/etds/lib/python2.7/site-packages/pymarc/reader.py", line 107, in __next__
    file_encoding = self.file_encoding)
  File "/apps/etds/lib/python2.7/site-packages/pymarc/record.py", line 75, in __init__
    encoding=file_encoding)
  File "/apps/etds/lib/python2.7/site-packages/pymarc/record.py", line 286, in decode_marc
    subs[0] = subs[0].decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 62: ordinal not in range(128)

**Comment by elopatin-uc3** [comment]
I suspect one of the two UNX files sent to us by ProQuest is causing this decoding error:
UC Irvine MARC Dec 2020.unx
UC Santa Cruz MARC Q3 2020.unx

I manually uploaded these for processing. When sorting the following directory chronologically, they appear at the top and are marked with the date that `createmarc.py` processing began error (Jan 15):
```
etds@uc3-etdx2-prd:~/apps/uc3-etds/marc$ ls -ltr
total 1824
-rw-r--r-- 1 etds etds 303799 Jan 15 15:59 UC Irvine MARC Dec 2020.unx
-rw-r--r-- 1 etds etds  79481 Jan 15 16:00 UC Santa Cruz MARC Q3 2020.unx
-rw-rw-r-- 1 etds etds   7084 Jan 18 13:31 ucla20210118-orig.xml
-rw-rw-r-- 1 etds etds   7084 Jan 19 13:31 ucla20210119-orig.xml
-rw-rw-r-- 1 etds etds   7084 Jan 20 13:31 ucla20210120-orig.xml
-rw-rw-r-- 1 etds etds   7054 Jan 21 13:31 ucsd20210121-orig.xml
....
```
I have backed these two files up in my home directory, and removed them from the `/marc` directory. The `createmarc` script runs each afternoon at 1:30PM. I'll look at it's log today to see if all other XML files were successfully processed into .mrc files.

**Comment by elopatin-uc3** [comment]
The `createmarc` script ran successfully at 1:30pm today.

**Comment by elopatin-uc3** [comment]
I have obtained .MRC files from ProQuest and have uploaded them to the ETDs box:
```
-rw-r--r-- 1 etds etds 303799 Feb 11 14:33 UC Irvine MARC Dec 2020.mrc
-rw-r--r-- 1 etds etds  79481 Feb 11 14:33 UC Santa Cruz MARC Q3 2020.mrc
```

I'll check tomorrow at 1:30 to ensure these processed. 

Note that ProQuest can easily change the output of the report that generates our records to save and send .mrc files, rather than .unx files. If these two new .mrc file process correctly, I will ask them to make the change.

**Comment by elopatin-uc3** [comment]
Processing the .mrc files failed for a different reason this time:
```
Starting createmarc at Fri Feb 12 13:30:02 PST 2021
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 975, in <module>
    main()
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 959, in main
    deliver_files(hostenv)
  File "/etds/apps/uc3-etds/scripts/createmarc.py", line 701, in deliver_files
    if ucabbr.group(1) == campusabbr:
AttributeError: 'NoneType' object has no attribute 'group'
Finished createmarc at Fri Feb 12 13:31:16 PST 2021
```
It appears one of the records is missing a campus code; will need to inspect with MarcEdit.

**Comment by cpwillett** [comment]
Hey Eric,
I noticed this one--this is probably another "feature" of my software that can be improved. I was counting on the MARC files delivered by Proquest to have a file extension of *.UNX or *.unx.  The filename should follow a pattern like this in regexp:
UC\s(.*?)\sMARC.*?
eg "UC Irvine MARC Q1 2021.UNX"
It worked great when I started with this, because there was a long-standing Proquest staff member who named the files consistently. But then he retired (sound familiar?). You'll see this section of the code in createmarc.py starting at line 459.

It could use a code from the MARC record to identify the campus (rather than the filename), but it would get a little complicated with the XSLT processing. You'd have to first read the file, find and interpret the code, and then process it with XSLT. It is a lot of work just to identify the campus. I'm sure there are better ways to do this. 
I also saw the issue you reported about unicode character encodings. I tried a lot of different ways to get the program to throw an error instead of just crapping out for these kinds of issues, but unfortunately I didn't succeed. Character encodings are hard. Sorry about that!
Perry

**Comment by elopatin-uc3** [comment]
Hey @cpwillett, it's good to hear from you.
Thanks for this note. I remember you mentioning the person who may have retired at Proquest. I've been renaming the files they send nowadays so that they conform more closely to what you'd mentioned in the documentation (but will try again with this file; thanks for the line reference). Character encoding is no fun; completely agree. Terry and I are wondering if it may be time to check on the version of `pymarc` we're using, or even...updating to Python3 and dealing with EZID and large file handling. Lots of other work going on though. 
Hope all's well! Eric

**Comment by cpwillett** [comment]
I've read that python3 would solve a lot of these character encoding problems. I looked into upgrading the code before I retired and it seemed manageable, but I was stymied in part by needing to upgrade the modified ezid.py code that is encorporated. Perhaps the EZID team has worked on this in the past 18 months.

**Comment by elopatin-uc3** [comment]
It turns out that the `createmarc` run on February 9th generated a few dozen duplicate records that made their way into UCLA's catalog. They unfortunately are having to deal with a significant amount of cleanup.
https://help.escholarship.org/a/tickets/85297

**Comment by elopatin-uc3** [comment]
The same occurred for UCSD: https://cdl.freshdesk.com/a/tickets/84768
However the duplicate records were caught before entering their catalog.

**Comment by terrywbrady** [comment]
@elopatin-uc3 I hope this can be closed
