### ISSUE TITLE
Intermittent gateway timeout issue affects eSchol ETD harvester (collection atom feeds)

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#704]
#### Summary
The following error occurs on an intermittent basis when the eSchol ETD harvest is accessing our atom feeds:

![gateway_timeout](https://user-images.githubusercontent.com/49419424/122477383-77ef5500-cf7c-11eb-86bd-c9a00a1fd2f5.png)

And related error message from daily ETD harvest notification email:
```
Exception fetching Merritt file: URLError(TimeoutError(110, 'Connection timed out'))
Item error: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib64/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/lib64/python3.7/http/client.py", line 1439, in connect
    super().connect()
  File "/usr/lib64/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

**Comment by mreyescdl** [comment]
The default value for an ALB "idle_timeout.timeout_seconds" is 60 seconds.
I increased it to 300, or 5 minutes.

Can we find out how long a connection needs to be from the Eschol folks?  @elopatin-uc3

**Comment by elopatin-uc3** [comment]
I can ask for some guidance from eschol on the timeout @mreyescdl ; will do

**Comment by terrywbrady** [comment]
A longer term solution that we could apply would be to look into the performance of the query that is timing out.  As we imagine moving to a true Merritt UI, I have presumed that all of the UI requests are now short-lived since we implemented presigned retrievals.  I wonder if we either need to tune a query or look at memory configuration on the UI boxes.

**Comment by terrywbrady** [comment]
I think we resolved this with the atom feed improvements.  Closing.
