### ISSUE TITLE
Inventory locking

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#783]
Two Inventory failures in stage can be attributed to table locking when content is being added to the inv database.

The two failures are 
- ark:/99999/fk4df86f3m
~~~
Wed Sep 01 15:43:48 PDT 2021    (02) [yyMMdd] SaveObject URL: - storageBase=http://store-stage.cdlib.org:35121 - node=9502 - objectID=ark:/99999/fk4df86f3m - role=primary - copyRole=null
Wed Sep 01 15:43:51 PDT 2021 ** (00) [yyMMdd] DBAdd: exec - Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='47',inv_object_id='97146' - exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
Wed Sep 01 15:43:51 PDT 2021 ** (00) [yyMMdd] DBAdd: Exception:org.cdlib.mrt.inv.utility.DBAdd-exec:310 SQL_EXCEPTION[SQL exception] Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='47',inv_object_id='97146' - exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction - Exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
Wed Sep 01 15:43:51 PDT 2021 ** (05) [yyMMdd] org.cdlib.mrt.inv.utility.DBAdd-exec:310 SQL_EXCEPTION[SQL exception] Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='47',inv_object_id='97146' - exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction - Exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at org.cdlib.mrt.inv.utility.DBAdd.exec(DBAdd.java:310)
~~~

- ark:/99999/fk48p7gn2f
~~~
Wed Sep 01 15:43:49 PDT 2021    (02) [yyMMdd] SaveObject URL: - storageBase=http://store-stage.cdlib.org:35121 - node=9502 - objectID=ark:/99999/fk48p7gn2f - role=primary - copyRole=null
Wed Sep 01 15:43:51 PDT 2021 ** (00) [yyMMdd] DBAdd: exec - Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='47',inv_object_id='97147' - exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
Wed Sep 01 15:43:51 PDT 2021 ** (00) [yyMMdd] DBAdd: Exception:org.cdlib.mrt.inv.utility.DBAdd-exec:310 SQL_EXCEPTION[SQL exception] Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='47',inv_object_id='97147' - exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction - Exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
Wed Sep 01 15:43:51 PDT 2021 ** (05) [yyMMdd] org.cdlib.mrt.inv.utility.DBAdd-exec:310 SQL_EXCEPTION[SQL exception] Exception - sql=insert into inv_collections_inv_objects set inv_collection_id='47',inv_object_id='97147' - exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction - Exception:com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at org.cdlib.mrt.inv.utility.DBAdd.exec(DBAdd.java:310)

~~~

Some earlier examples of locking appeared to be related to concurrent updates on the same object. This is definitely a table lock problem.  

Investigation is needed to identify a solution that avoids resubmitting with repeated locking.

**Comment by dloy** [comment]
Note for this problem:
[InnoDB tables use row-level locking](https://dev.mysql.com/doc/refman/8.0/en/table-locking.html)

The inv_collections_inv_objects table is defined: ENGINE=InnoDB

**Comment by terrywbrady** [comment]
@dloy - can this be closed now that Mark's locking mechanism is in place?
