### ISSUE TITLE
Investigate why UC Davis ETDs are not being successfully submitted to Merritt

### ISSUE THREAD

**Issue by elopatin-uc3** [CDLUC3/mrt-doc#824]
First UCD ETD arrived on 10/7: etdadmin_upload_711198.zip

It is still sitting in the /zipfiles folder, but should have been ingested.

Investigate why this occurred.

**Comment by elopatin-uc3** [comment]
Seeing more than one occurrence of this error in the etds.log:
```
2021-10-13 07:30:33,051 ERROR submitting to Merritt: 404 Client Error: Not Found for url: https://merritt.cdlib.org/object/update/
Traceback (most recent call last):
  File "/etds/apps/uc3-etds/scripts/getetds.py", line 253, in submit_to_merritt
    req.raise_for_status()
  File "/apps/etds/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://merritt.cdlib.org/object/update/
```

**Comment by elopatin-uc3** [comment]
Checked ingest profile changes and they look correct:
https://github.com/cdlib/mrt-ingest-profile/commit/d85a6ae7eb8c4d00dd2e285942300bed201fd4e2

**Comment by elopatin-uc3** [comment]
The etd submission user was not assigned to the collection in LDAP. This has been corrected and a test object submitted successfully via curl (and then deleted). The next getetds run should ingest all UCD ETDs.
