### ISSUE TITLE
[Ingest] Batch submission does not complete due to data retrieval core lib hanging

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#892]
Large Batch submission does not complete.  Logs shows continual logging of

awaiting completion of retrievals.... Thread: pool-1-thread-4
awaiting completion of retrievals.... Thread: pool-1-thread-2
awaiting completion of retrievals.... Thread: pool-1-thread-1

Ingest handler HandlerRetrieve attempts download 3 times before throwing an error.  However, prior to this a low level socket read hangs and the exception is never thrown and batch does not complete.

Using "jstack" java utility, we can see the following trace which confirms that threads are indeed hung.
$ jstack 16946

"pool-109-thread-4" #760 prio=5 os_prio=0 tid=0x00007fe3d004a000 nid=0x4c77 runnable [0x00007fe3c639d000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)
        at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:237)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1363)
        at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73)
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:957)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:200)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:150)
        at org.cdlib.mrt.utility.HttpGet.stream2File(HttpGet.java:302)
        at org.cdlib.mrt.utility.HttpGet.buildContentLength(HttpGet.java:184)
        at org.cdlib.mrt.utility.HttpGet.build(HttpGet.java:134)
        at org.cdlib.mrt.utility.HttpGet.getFile(HttpGet.java:62)
        at org.cdlib.mrt.utility.FileUtil.url2File(FileUtil.java:69)
        at org.cdlib.mrt.utility.FileUtil.url2File(FileUtil.java:105)
        at org.cdlib.mrt.ingest.handlers.RetrieveData.call(HandlerRetrieve.java:456)
        at org.cdlib.mrt.ingest.handlers.RetrieveData.call(HandlerRetrieve.java:421)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by mreyescdl** [comment]
Ingest uses the Merritt core library "org.cdlib.mrt.utility.FileUtil.url2File" to retrieve manifest data.
Online querying of this issue suggests to put a socket timeout on the retrieval so it will eventually fail.

(https://stackoverflow.com/questions/28785085/how-to-prevent-hangs-on-socketinputstream-socketread0-in-java)

**Comment by elopatin-uc3** [comment]
Discussed in 1/3/22 team meeting. Not a high priority, but David will look into adding a timeout after he finishes up separate Storage Admin tasks.
