### ISSUE TITLE
[Ingest] - Notification failed with Null Pointer Exception

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#944]
Escholarship job failed with Null pointer exception in Notification Handler.
Looks like the BatchState object was corrupted.  At this point we'll just note the occurrence.
Here is the line of failure and the stack trace

```
if (BatchState.getBatchCompletion(batchID) == BatchState.getBatchState(batchID).getJobStates().size()) {
```

```
java.lang.NullPointerException
        at org.cdlib.mrt.ingest.handlers.HandlerNotification.handle(HandlerNotification.java:115)
        at org.cdlib.mrt.ingest.handlers.HandlerNotification.handle(HandlerNotification.java:64)
        at org.cdlib.mrt.ingest.IngestManager.submit(IngestManager.java:605)
        at org.cdlib.mrt.ingest.service.IngestService.submit(IngestService.java:90)
        at org.cdlib.mrt.ingest.consumer.ConsumeData.run(Consumer.java:617)
```

**Comment by terrywbrady** [comment]
@mreyescdl - closing for now
