### ISSUE TITLE
[Ingest] Refactor and dependabot upgrade

### ISSUE THREAD

**Issue by mreyescdl** [CDLUC3/mrt-doc#949]
Multiple tasks involving migrating to new Jenkins pipeline and general cleaning up of environment

**Comment by mreyescdl** [comment]
Stage Ingest now deployed using new Jenkins pipeline

**Comment by mreyescdl** [comment]
Added dependabot updates to Ingest branch "java-refactor"

**Comment by mreyescdl** [comment]
Merged java-refactor to main in cdl zookeeper lib (also updated dependabot libs)

**Comment by mreyescdl** [comment]
Removed "master" from mrt-core2

**Comment by mreyescdl** [comment]
Merged "java-refactor" to main for mrt-core2

Did *NOT* update dependabot alerts.  Will discuss with David before doing so

**Comment by mreyescdl** [comment]
Note:  I modified settings.xml on the builds server to use both the Local Nexus maven repo and the Central maven repo
This will allow "legacy" jobs to succeed (cdl ZK job, core 2)

**Comment by mreyescdl** [comment]
Merged branch "java-refactor" into main.  
Built and confirmed that Ingest and its dependencies are now using main branches.

**Comment by mreyescdl** [comment]
Removed obsolete branches from mrt-ingest repo

**Comment by mreyescdl** [comment]
Tagged, build and deployed to Stage

**Comment by mreyescdl** [comment]
Prepared Ingest production for new pipeline, but have not deployed.
- New tomcat8_catalina_base branch for Ingest prod service level
- New mrt-tomcat prod Ingest cap file
- New semantic deployment script for ingest01/ingest02/ingest03 that takes a tag input

**Comment by mreyescdl** [comment]
Added build.content.txt retrieval to Stage Ingest

**Comment by mreyescdl** [comment]
Production Ingest redeployment complete.  Tag - 0.0.20

**Comment by elopatin-uc3** [comment]
Thanks @mreyescdl !

**Comment by mreyescdl** [comment]
Rollback required due to failures.

**Error:** 
```
 java.lang.NoClassDefFoundError: org/jdom/Content
        at org.cdlib.mrt.ingest.utility.StorageUtil.getVersionMap(StorageUtil.java:197)
        at org.cdlib.mrt.ingest.handlers.HandlerDescribe.updateModel(HandlerDescribe.java:873)
        at org.cdlib.mrt.ingest.handlers.HandlerDescribe.updateResourceMap(HandlerDescribe.java:724)
```
**Analysis:**
This caused by upgrading JDOM artifact from 1.1 to 2.0.2 as suggested by Dependabot.
In this upgrade, class path was changed from:
    was:  org.jdom
    now:  org.jdom2
This new path requires code changes. 

Note:
- There was no compilation error due to Ingest accessing this library through the core2 library.  It would only be found at runtime.
- Updating core2 would have caused the compilation error, but was not done in tandem with Ingest.
- Testing in stage did not detect the error as the offending code is only used when updating an existing object (version 2)

To do:  
- Add an object update to testing
- Read release notes for all updated artifacts

**Comment by mreyescdl** [comment]
Terry created a version test in the Integration Suite.    Thanks @terrywbrady 


Upgraded Stage with official rollback of JDOM artifact ```https://github.com/CDLUC3/mrt-ingest/pull/44```
Tag 0.0.21
Test succeeds on Stage.

To do: Update to tag 0.0.21 in production next week

**Comment by mreyescdl** [comment]
Production workers updated with tag 0.0.21

**Comment by terrywbrady** [comment]
@elopatin-uc3 - please close with whatever labeling is needed

**Comment by elopatin-uc3** [comment]
@terrywbrady Done, but will remove from the board after next week's sprint planning.
